spring:
  application:
    name: sola-transaction
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${O2_SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/transaction_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8}
    username: ${O2_SPRING_DATASOURCE_USERNAME:root}
    password: ${O2_SPRING_DATASOURCE_PASSWORD:zhanpeng}
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:5}
      # 连接池允许的最大连接数
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:10}
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:30000}